HBSP 335 support custom widgets in blog posts
Smartling/hubspot-rest-sdk-java pull request #30
Opened 2021-01-13 16:59 UTC by kdudina-smartling

MERGED from HBSP-326-Blog-post-processing

2021-01-13 23:33 UTC, dimitrystd requested changes
Left comments in another review. I expect that some methods will be deleted as unused

2021-01-13 23:33 UTC, dimitrystd commented on src/main/java/com/smartling/connector/hubspot/sdk/rest/api/BlogPostsRawApi.java
> +    @RequestLine("GET /content/api/v2/blog-posts/{blog_post_id}")
Why v2 when hubspot uses v3. Please check that new version works by tests.
We implement a brand new functionality that will be fully tested manually. So why lose the opportunity and use legacy API that someone will have to update (when hubspot will send a notice)
![image](https://user-images.githubusercontent.com/1511122/104525056-653bb300-55cd-11eb-8e5d-021991dfbc8c.png)

2021-01-14 09:06 UTC, sl-mmuradov commented on src/main/java/com/smartling/connector/hubspot/sdk/rest/api/BlogPostsRawApi.java
> +    @RequestLine("GET /content/api/v2/blog-posts/{blog_post_id}")
We use V2 API for now. I would migrate to V3 API by separate task/PR.

2021-01-15 15:03 UTC, kdudina-smartling commented on src/main/java/com/smartling/connector/hubspot/sdk/rest/api/BlogPostsRawApi.java
> +    @RequestLine("GET /content/api/v2/blog-posts/{blog_post_id}")
V3 is in beta currently - https://developers.hubspot.com/docs/api/cms/blog-post?_ga=2.114834759.1334556895.1610638711-771452351.1610450942. Also model changed a lot.

2021-01-15 21:47 UTC, dimitrystd requested changes

2021-01-15 21:47 UTC, dimitrystd commented on src/main/java/com/smartling/connector/hubspot/sdk/rest/api/BlogPostsRawApi.java
> +    @RequestLine("GET /content/api/v2/blog-posts/{blog_post_id}")
ok, this is a solid reason. Someone will be unlucky in the future :)

2021-01-15 21:47 UTC, dimitrystd commented on src/integrationTest/java/com/smartling/connector/hubspot/sdk/it/BlogPostsIntegrationTest.java
> -    public void shouldCloneBlogPost() throws HubspotApiException {
We still have Clone and Delete methods in API but no simple ways to run tests for these methods anymore.

2021-01-15 21:47 UTC, dimitrystd commented on src/main/java/com/smartling/connector/hubspot/sdk/rest/api/BlogPostsRawApi.java
> +    String create(String blogPostAsJson);
Nitpick. The new raw api uses another method name pattern (inconsistent with another API client). Compare new `create` with old `createBlogPost`.

2021-01-18 09:11 UTC, sl-mmuradov approved these changes

2021-01-18 10:39 UTC, kdudina-smartling commented on src/main/java/com/smartling/connector/hubspot/sdk/rest/api/BlogPostsRawApi.java
> +    String create(String blogPostAsJson);
Removed create method at all because it is not needed anymore

2021-01-18 11:52 UTC, dkBrazz approved these changes

2021-01-18 14:21 UTC, merged